### ISSUE TITLE
execute only on internet connection

### ISSUE THREAD

**Issue by yveveke** [ImmobilienScout24/kiosk-browser#5]
in the .xsession file, is it possible to check if the kiosk has internet connection, and only then launch the browsers?
Or to show a standard local html page with the message "connecting to the internet" and when the machine has connection press F5 with xdotool.

**Comment by schlomo** [comment]
A couple of months ago I added code to wait for some time to give the network more time to start. Probably not going to solve all your problems, though.

If you want to have something more elaborate then please provide a pull request.
